const colors = {
  light: {
    text: "#111827",
    tint: "#7C3AED",
    background: "#F7F6FB",
    foreground: "#111827",
    card: "#FFFFFF",
    cardForeground: "#111827",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    primaryLight: "#EDE9FE",
    secondary: "#F3F4F6",
    secondaryForeground: "#374151",
    muted: "#F3F4F6",
    mutedForeground: "#6B7280",
    accent: "#A78BFA",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5E7EB",
    input: "#E5E7EB",
    success: "#16A34A",
    successLight: "#DCFCE7",
    warning: "#F59E0B",
    leakRed: "#DC2626",
    leakRedLight: "#FEF2F2",
    leakOrange: "#EA580C",
    leakOrangeLight: "#FFF7ED",
    leakYellow: "#CA8A04",
    leakYellowLight: "#FEFCE8",
    purpleGradientStart: "#7C3AED",
    purpleGradientEnd: "#A855F7",
  },
  radius: 12,
};

export default colors;
