/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/history`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/sms-results`; params?: Router.UnknownInputParams; } | { pathname: `/sms-scanning`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/connect-accounts` | `/connect-accounts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/consent` | `/consent`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/features` | `/features`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/language` | `/language`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/budget` | `/budget`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sms-scan` | `/sms-scan`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/history`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/sms-results`; params?: Router.UnknownOutputParams; } | { pathname: `/sms-scanning`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/connect-accounts` | `/connect-accounts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/consent` | `/consent`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/features` | `/features`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/language` | `/language`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/budget` | `/budget`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sms-scan` | `/sms-scan`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/history${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/sms-results${`?${string}` | `#${string}` | ''}` | `/sms-scanning${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/connect-accounts${`?${string}` | `#${string}` | ''}` | `/connect-accounts${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/consent${`?${string}` | `#${string}` | ''}` | `/consent${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/features${`?${string}` | `#${string}` | ''}` | `/features${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/language${`?${string}` | `#${string}` | ''}` | `/language${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/budget${`?${string}` | `#${string}` | ''}` | `/budget${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sms-scan${`?${string}` | `#${string}` | ''}` | `/sms-scan${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/history`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/sms-results`; params?: Router.UnknownInputParams; } | { pathname: `/sms-scanning`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/connect-accounts` | `/connect-accounts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/consent` | `/consent`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/features` | `/features`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/language` | `/language`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/budget` | `/budget`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sms-scan` | `/sms-scan`; params?: Router.UnknownInputParams; };
    }
  }
}
